### ISSUE TITLE
we are missing "build instructions"

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/ardusub-zola#72]
I did:
`sudo pacman -S zola`
`git submodule update --init --recursive`
`zola serve -i 0.0.0.0` (testing from another computer)

But I apparently got no css. am I missing something?

**Comment by ES-Alexander** [comment]
I would expect such instructions to be covered by #2, so I think this is a duplicate issue?

> I did:
> ...
> But I apparently got no css. am I missing something?

I generally `zola serve` without `-i`, and I installed zola using `brew`, but otherwise the same and it works fine for me. Note that building/serving should be done from the root of the `master` branch - if you're in a different directory or branch then it likely won't work. 

Are you saying the generated site wasn't formatted, or that you specifically couldn't find any css files in the source? Adidoks (the theme we're using) uses [Sass](https://sass-lang.com/documentation/) stylesheets, which are `.scss` files, if that's relevant.

**Comment by Williangalvani** [comment]
> I generally `zola serve` without `-i`, and I installed zola using `brew`, but otherwise the same and it works fine for me. Note that building/serving should be done from the root of the `master` branch - if you're in a different directory or branch then it likely won't work.

This is the issue, I was on a branch based on your PR

**Comment by ES-Alexander** [comment]
More detailed process [here](https://github.com/bluerobotics/cockpit/pull/747#issuecomment-1958741434)

**Comment by ES-Alexander** [comment]
[Provided in new contributing docs](https://github.com/bluerobotics/BlueOS-docs/blob/latest/CONTRIBUTING.md#local-setup)
